export const ADD_INCOMING_PROJECT = 'ADD_INCOMING_PROJECT'

export const REMOVE_INCOMING_PROJECT = 'REMOVE_INCOMING_PROJECT'

export const CATCH_INCOMING_ERROR = 'CATCH_INCOMING_ERROR'

export const SET_PROJECT_IS_BEING_ADDED = 'SET_PROJECT_IS_BEING_ADDED'
